title: Coduinix
description: Some of my thoughts on programming
name: Coduinix

exclude:
  - README.md

# Installed gems
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed

remote_theme: daviddarnes/alembic
css_inline: true

# Gem settings
twitter:
  username: coduinix
author: Coduinix

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike

#  Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
feature_image: "https://picsum.photos/2560/600?image=866"

# Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  About: /about/
  Categories: /categories/
  Search: /search/


navigation_footer:
  Created by Coduinix: https://coduinix.github.com