title: Coduinix
description: Me and the art of coding
name: Coduinix

exclude:
  - README.md
  - .idea
  - Gemfile
  - Gemfile.lock

# Installed gems
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.20.2
minimal_mistakes_skin: "contrast"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/coduinix"

css_inline: false

# Gem settings
twitter:
  username: coduinix
author:
  name: "Hinse ter Schuur"
  bio: "Hinse is a Software Engineer at SDB Java. Over the years he has done a lot of Java and Scala coding. He loves to share his experience by doing pair programming, reviews, writing articles and giving talks."
  avatar: "/assets/images/bio-photo.jpg"
  location: "Waddinxveen, The Netherlands"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/coduinix"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://fosstodon.org/@coduinix"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/coduinix"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hinseterschuur"
social:
  name: Coduinix
  links:
    - https://twitter.com/coduinix
    - https://github.com/coduinix

# Jekyll settings
sass:
  style: compressed # Style compression

permalink: /:categories/:title
paginate: 5
paginate_path: /page:num/
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
