title: Coduinix
description: Me and the art of coding
name: Coduinix

exclude:
  - README.md
  - .idea
  - Gemfile
  - Gemfile.lock

# Installed gems
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.20.2
minimal_mistakes_skin: "dark"

css_inline: false

# Gem settings
twitter:
  username: coduinix
author:
  name: "Hinse ter Schuur"
  bio: "Hinse is a Software Engineer at SDB Java. Over the years he has done a lot of Java and Scala coding. He loves to share his experience by doing pair programming, reviews, writing articles and giving talks."
  avatar: "/assets/images/bio-photo.jpg"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
social:
  name: Coduinix
  links:
    - https://twitter.com/coduinix
    - https://github.com/coduinix

# Jekyll settings
sass:
  style: compressed # Style compression

permalink: /:categories/:title
paginate: 5
paginate_path: /page:num/
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike


# Site navigation
navigation_header:
  Blog: /
  Categories: /categories
  About: /about

navigation_footer:
  Created by Coduinix: https://coduinix.github.com

twitter:
  username: coduinix

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
